use_frameworks!

ios_deployment_target = '14.0'

target 'IOS-Test-Task' do
  pod 'TinyConstraints', '4.0.2'
  pod 'PKHUD', '5.3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < ios_deployment_target.to_f
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_deployment_target
        end
      end
    end
  end
end
